# Generated by Django 4.2.7 on 2026-02-04 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identifier', max_length=20, unique=True, validators=[employees.models.validate_employee_id])),
                ('full_name', models.CharField(help_text='Full name of the employee', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the employee', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='employees_a_employe_030d17_idx'), models.Index(fields=['date'], name='employees_a_date_b8bb7b_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
